spring.application.name=GhostBusters
springdoc.swagger-ui.path=/docs
spring.datasource.url=jdbc:postgresql://ghostbus-ters-ghostbus-ters.e.aivencloud.com:27532/defaultdb?currentSchema=transit&sslmode=require
spring.datasource.username=${AIVEN_DB_USERNAME}
spring.datasource.password=${AIVEN_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
snowflake.url=jdbc:snowflake://xycbdis-he21700.snowflakecomputing.com/?warehouse=GHOSTBUS_WH&db=GHOSTBUS_DB&schema=PUBLIC
snowflake.user=ruttergutter
snowflake.password=IDontCareAboutThis1