spring.application.name=GhostBusters
springdoc.swagger-ui.path=/docs
spring.datasource.url=jdbc:postgresql://bpee13mbjm.jinbdnocfw.tsdb.cloud.timescale.com:37968/tsdb?currentSchema=transit&sslmode=require
spring.datasource.username=tsdbadmin
spring.datasource.password=ghostbusmiami
spring.datasource.driver-class-name=org.postgresql.Driver
snowflake.url=jdbc:snowflake://xycbdis-he21700.snowflakecomputing.com/?warehouse=GHOSTBUS_WH&db=GHOSTBUS_DB&schema=PUBLIC
snowflake.user=ruttergutter
snowflake.password=IDontCareAboutThis1